### ISSUE TITLE
Unable to push new branch to add a corpus via a PR

### ISSUE THREAD

**Issue by mkouts** [Breakend/DialogDatasets#10]
Hi all,

I am trying to push to a new branch changes to the pages that reflect addition of a new corpus (multisimo). However, I am denied access to push. Can you please advise what is the designated way to add a new corpus? 

Link to error:

```
192:DialogDatasets koutsomm$ git push
ERROR: Permission to Breakend/DialogDatasets.git denied to mkouts.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Breakend** [comment]
Hi, I think you've got to create a fork, push to the fork and then create a pull request that way

**Comment by mkouts** [comment]
Thank you very much, it worked!

**Comment by Breakend** [comment]
Awesome, closing the issue then!
