### ISSUE TITLE
Any datasets which have fixed number of responses to choose from for NUC (Next utterance classification) task  

### ISSUE THREAD

**Issue by prernakhurana2** [Breakend/DialogDatasets#2]
I need a dataset in which we can simply classify the last n utterances into which class they belong, and a fixed response is tagged to that class. The dataset should not have slot filling or state detection.

**Comment by Breakend** [comment]
i'm really not sure what you're looking for, sorry. You can browse through the datasets we've described in the paper and website or add one if you find something you're looking for. It sounds like you're looking for something like span-detection though?
